# Minimal-viable hardware-configuration fixture for closure-build CI.
#
# Production `nixosConfigurations.ovh-test` defers `fileSystems."/"`
# and the boot-initrd module list to the per-instance
# `hardware-configuration.nix` generated by `nixos-anywhere
# --generate-hardware-config` at install time. That file is read from
# the `PHAROS_HARDWARE_CONFIG` env var via `builtins.getEnv` under
# `--impure` (see `flake.nix`'s `nixosConfigurations.ovh-test` block).
#
# In CI's pure-mode evaluation no hardware-config is loaded, so the
# closure isn't buildable without a stub source for these mandatory
# options. This fixture supplies the bare minimum NixOS asserts on at
# eval time — JUST enough for `system.build.toplevel` to realise —
# and is layered onto the production module list via `extendModules`
# in `checks.deployment-build` only. It is never deployed to a real
# host.
#
# `lib.mkDefault` priority ensures a real hardware-configuration's
# values win the automatic merge if both this fixture and a real
# config are layered into the same evaluation.
{ lib, ... }:
{
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos-root";
    fsType = "ext4";
  };
  boot.initrd.availableKernelModules = lib.mkDefault [ ];
}
